version: 2.1

orbs:
  cimg: circleci/cimg@0.3.0

workflows:
  main-wf:
    jobs:
      - cimg/build-and-deploy:
          name: "Test"
          docker-namespace: ccitest
          docker-repository: clojure
          filters:
            branches:
              ignore:
                - main
          context: cimg-docker-image-building
      - cimg/build-and-deploy:
          name: "Deploy"
          docker-repository: clojure
          filters:
            branches:
              only:
                - main
          context:
            - cimg-docker-image-building
            - cimg-docker-image-publishing
            
