version: 2.1

orbs:
  cimg: circleci/cimg@0.6.5

parameters:
  cron:
    type: boolean
    default: false

workflows:
  automated-wf:
      when: << pipeline.parameters.cron >>
      jobs:
        - cimg/update:
            update-script: clojureFeed.sh
            context:
              - slack-notification-access-token
              - slack-cimg-notifications
              - cpe-image-bot-github-creds

  main-wf:
    when:
      not: << pipeline.parameters.cron >>
    jobs:
      - cimg/build-and-deploy:
          name: "Test"
          docker-namespace: ccitest
          docker-repository: clojure
          filters:
            branches:
              ignore:
                - main
          context: 
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
      - cimg/build-and-deploy:
          name: "Deploy"
          docker-repository: clojure
          filters:
            branches:
              only:
                - main
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
            - cimg-docker-image-publishing
            
